# pybind11 superbuild

# Set dependency list
ome_add_dependencies(pybind11
                     THIRD_PARTY_PYTHON2_DEPENDENCIES numpy pytest)

list(APPEND CONFIGURE_OPTIONS -Wno-dev --no-warn-unused-cli -DPYBIND11_TEST:BOOL=OFF)
string(REPLACE ";" "^^" CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS}")

ExternalProject_Add(${EP_PROJECT}
  ${OME_EP_COMMON_ARGS}
  URL "https://github.com/pybind/pybind11/archive/v2.2.2.tar.gz"
  URL_HASH "SHA512=abc7bd1b27945ab25cd818126454d073f6e6bacf73f733cc686ab2eb0ceedba028fc261803916af001d2c658a7097da1aa292759f311fbc7ab23f971f7b7231f"
  SOURCE_DIR "${EP_SOURCE_DIR}"
  BINARY_DIR "${EP_BINARY_DIR}"
  INSTALL_DIR ""
  CONFIGURE_COMMAND ${CMAKE_COMMAND}
    "-DSOURCE_DIR:PATH=${EP_SOURCE_DIR}"
    "-DBUILD_DIR:PATH=${EP_BINARY_DIR}"
    "-DCONFIG:INTERNAL=$<CONFIG>"
    "-DEP_SCRIPT_CONFIG:FILEPATH=${EP_SCRIPT_CONFIG}"
    "-DCONFIGURE_OPTIONS=${CONFIGURE_OPTIONS}"
    -P "${GENERIC_CMAKE_CONFIGURE}"
  BUILD_COMMAND ${CMAKE_COMMAND}
    "-DSOURCE_DIR:PATH=${EP_SOURCE_DIR}"
    "-DBUILD_DIR:PATH=${EP_BINARY_DIR}"
    "-DCONFIG:INTERNAL=$<CONFIG>"
    "-DEP_SCRIPT_CONFIG:FILEPATH=${EP_SCRIPT_CONFIG}"
    -P "${GENERIC_CMAKE_BUILD}"
  INSTALL_COMMAND ${CMAKE_COMMAND}
    "-DSOURCE_DIR:PATH=${EP_SOURCE_DIR}"
    "-DBUILD_DIR:PATH=${EP_BINARY_DIR}"
    "-DCONFIG:INTERNAL=$<CONFIG>"
    "-DEP_SCRIPT_CONFIG:FILEPATH=${EP_SCRIPT_CONFIG}"
    -P "${GENERIC_CMAKE_INSTALL}"
#  TEST_COMMAND ${CMAKE_COMMAND}
#    "-DSOURCE_DIR:PATH=${EP_SOURCE_DIR}"
#    "-DBUILD_DIR:PATH=${EP_BINARY_DIR}"
#    "-DCONFIG:INTERNAL=$<CONFIG>"
#    "-DEP_SCRIPT_CONFIG:FILEPATH=${EP_SCRIPT_CONFIG}"
#    -P "${CMAKE_CURRENT_LIST_DIR}/test.cmake"
  DEPENDS
    ${EP_PROJECT}-prerequisites
)
