# pybind11 superbuild

# Set dependency list
ome_add_dependencies(pybind11
                     THIRD_PARTY_PYTHON2_DEPENDENCIES numpy pytest)

list(APPEND CONFIGURE_OPTIONS -Wno-dev --no-warn-unused-cli -DPYBIND11_TEST:BOOL=OFF)
string(REPLACE ";" "^^" CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS}")

ExternalProject_Add(${EP_PROJECT}
  ${OME_EP_COMMON_ARGS}
  URL "https://github.com/pybind/pybind11/archive/v2.1.1.tar.gz"
  URL_HASH "SHA512=9c1493fabd0e38f5e46bc94d78e3e4e735e81b309a403a5c6060527d21b0c4ce5081f4eb4861258897ca01cca3e9cb2770f4e844d9222671b6f2ec8dd1dbe047"
  SOURCE_DIR "${EP_SOURCE_DIR}"
  BINARY_DIR "${EP_BINARY_DIR}"
  INSTALL_DIR ""
  CONFIGURE_COMMAND ${CMAKE_COMMAND}
    "-DSOURCE_DIR:PATH=${EP_SOURCE_DIR}"
    "-DBUILD_DIR:PATH=${EP_BINARY_DIR}"
    "-DCONFIG:INTERNAL=$<CONFIG>"
    "-DEP_SCRIPT_CONFIG:FILEPATH=${EP_SCRIPT_CONFIG}"
    "-DCONFIGURE_OPTIONS=${CONFIGURE_OPTIONS}"
    -P "${GENERIC_CMAKE_CONFIGURE}"
  BUILD_COMMAND ${CMAKE_COMMAND}
    "-DSOURCE_DIR:PATH=${EP_SOURCE_DIR}"
    "-DBUILD_DIR:PATH=${EP_BINARY_DIR}"
    "-DCONFIG:INTERNAL=$<CONFIG>"
    "-DEP_SCRIPT_CONFIG:FILEPATH=${EP_SCRIPT_CONFIG}"
    -P "${GENERIC_CMAKE_BUILD}"
  INSTALL_COMMAND ${CMAKE_COMMAND}
    "-DSOURCE_DIR:PATH=${EP_SOURCE_DIR}"
    "-DBUILD_DIR:PATH=${EP_BINARY_DIR}"
    "-DCONFIG:INTERNAL=$<CONFIG>"
    "-DEP_SCRIPT_CONFIG:FILEPATH=${EP_SCRIPT_CONFIG}"
    -P "${GENERIC_CMAKE_INSTALL}"
#  TEST_COMMAND ${CMAKE_COMMAND}
#    "-DSOURCE_DIR:PATH=${EP_SOURCE_DIR}"
#    "-DBUILD_DIR:PATH=${EP_BINARY_DIR}"
#    "-DCONFIG:INTERNAL=$<CONFIG>"
#    "-DEP_SCRIPT_CONFIG:FILEPATH=${EP_SCRIPT_CONFIG}"
#    -P "${CMAKE_CURRENT_LIST_DIR}/test.cmake"
  DEPENDS
    ${EP_PROJECT}-prerequisites
)
