#!/bin/sh
#
# Build with Jenkins CI.  This script is intended for use with the OME
# Jenkins CI infrastructure, though it may be useful as an example for
# how one might use various cmake options.
#
################################################################################

set -e

# Get OS name and version
os_version() {
  system="$(uname -s)"
  machine="$(uname -m)"

  case "$system" in
      Linux*)
          echo "$(lsb_release -si | sed -e 's;[[:space:]]*;;g')$(lsb_release -sr | sed -e 's;[[:space:]]*;;g' | sed -e 's;^\([^.][^.]*\)\.\([^.][^.]*\).*;\1.\2;')-$machine"
          ;;
      FreeBSD*)
          echo "$(freebsd-version | sed -e 's;\([^-]*\)-.*;FreeBSD\1;')-$machine"
          ;;
      Darwin*)
          echo "$(sw_vers | grep ^ProductVersion: | sed -e 's;^ProductVersion:[[:space:]]*\(.*\)\.\(.*\)\.\(.*\);MacOSX\1.\2;')-$machine"
          ;;
      *)
          echo "$(uname -sr | sed -e 's;[[:space:]]*;;g')-$machine"
          ;;
      esac
}

# Make source release
# $1=version
# $2=git branch
make_source_release() {
    (
        cd "${sourcedir}"
        mkdir -p "$artefactdir"
        git archive "--prefix=ome-cmake-superbuild-$1/" "$2" | xz > "${artefactdir}/ome-cmake-superbuild-$1.tar.xz"
    )
}

current_tree() {
    (
        cd "${sourcedir}"
        git log -1 --pretty=%T "$git_branch" --
    )
}

cached_tree() {
    [ -f "${cachedir}/tree" ] && cat "${cachedir}/tree"
}

save_tree() {
  echo "$(current_tree)" > "${cachedir}/tree"
}

make_cache() {
    rm -rf "${cachedir}/build"
    rm -rf "${cachedir}/python"
    cp -a "superbuild-install" "${cachedir}/build"
    cp -a "python" "${cachedir}/python"
    save_tree
}

# Purge cache if required
# Create cache dir, including source cache
check_cache_validity() {

    echo "Current tree: $(current_tree)"
    echo "Cached tree: $(cached_tree)"

    PURGE_SOURCE=false
    PURGE_BUILD=true
    if [ "$purge" = "all" ] || [ "$purge" = "source" ]; then
        echo "Requested purging of source cache"
        PURGE_SOURCE=true
    fi

    if [ -n "$(cached_tree)" ]; then
        if [ "$purge" = "all" ] || [ "$purge" = "build" ]; then
            echo "Requested purging of build cache"
        elif [ "$(current_tree)" != "$(cached_tree)" ]; then
            echo "Changes made; purging build cache"
        else
            echo "No changes; retaining build cache"
            PURGE_BUILD=false
        fi
    else
        echo "Build cache not present or incomplete"
    fi

    if [ "$PURGE_SOURCE" = "true" ]; then
        rm -rf "${cachedir}/source"
    fi

    if [ "$PURGE_BUILD" = "true" ]; then
        rm -rf "${cachedir}/build"
        rm -rf "${cachedir}/python"
        rm -rf "${cachedir}/tree"
    fi

    mkdir -p "${cachedir}/source"
}

# Run build
build() {
    # Use build cache if present; set environment so it's detected by
    # cmake and exclude cached prerequisites from build.  Note that
    # since gtest isn't installed and cached, so we still need to
    # build it.
    CMAKE_PREREQS="-Dbuild-prerequisites:BOOL=ON"
    if [ "$build_tp_prereqs" = "OFF" ] || [ -n "$(cached_tree)" ]; then
        CMAKE_PREREQS="-Dbuild-prerequisites:BOOL=OFF -Dome-superbuild_BUILD_gtest:BOOL=ON"
        if [ -n "$(cached_tree)" ]; then
            CMAKE_PREREQS="${CMAKE_PREREQS} -Dbuild-cache:PATH=${cachedir}/build -Dpython-cache:PATH=${cachedir}/python"
        fi
    fi

    GIT_OPTIONS=
    if [ "$build_git" = "ON" ];then
        GIT_OPTIONS="-Dome-xml-dir=${workspace}/ome-xml -Dome-files-dir=${workspace}/ome-files -Dome-common-dir=${workspace}/ome-common"
    fi

    rm -rf "$builddir" "$installdir"
    mkdir -p "$builddir" "$installdir"

    (
        cd "$builddir"
        # Note that due to using a local git mirror, the ome-xml-git-branch
        # is HEAD since it's already at the correct commit
        cmake \
            -G "$build_system" \
            -DCMAKE_VERBOSE_MAKEFILE:BOOL="$verbose" \
            -DCMAKE_BUILD_TYPE="$build_type" \
            -DCMAKE_INSTALL_PREFIX:PATH=${installdir}/stage \
            ${GIT_OPTIONS} \
            -Dcxxstd-autodetect="$cxxdetect" \
            "-Ddoxygen:BOOL=$doxygen" \
            "-Dextended-tests:BOOL=$extended_tests" \
            -Dqtgui:BOOL=OFF \
            -Dsphinx:BOOL=ON \
            -Dsphinx-pdf:BOOL=OFF \
            -Dsource-cache:PATH=${cachedir}/source \
            ${CMAKE_PREREQS} \
            ${sourcedir}

        # Make and cache prerequisites if missing
        if [ "$build_tp_prereqs" = "ON" ] && [ -z "$(cached_tree)" ]; then
            echo "Building prerequisites"
            cmake --build . --target third-party-prerequisites -- $parallel
            make_cache
        fi

        # Build superbuild (and run tests)
        echo "Building everything"
        cmake --build . -- $parallel

        # Install
        echo "Installing"
        cmake --build . --target install -- $parallel
    )

    # Release version
    eval $(cat "${builddir}/ome-files-build/config")
    version_tag="${OME_VERSION}-${build_type}-$(os_version)"
    echo "Built and installed version ${version_tag}"

    echo "Renaming staged install to ome-files-bundle-${version_tag}"
    rm -rf "${installdir}/ome-files-bundle-${version_tag}"
    mv "${installdir}/stage" "${installdir}/ome-files-bundle-${version_tag}"

    for component in ome-common ome-xml ome-files; do
        if [ -d "${builddir}/${component}-build/docs/doxygen/${component}" ]; then
            echo "Installing doxygen documentation for ${component}"
            cp -r "${builddir}/${component}-build/docs/doxygen/${component}" "${installdir}/ome-files-bundle-apidoc-${OME_VERSION}"
        fi
    done

    # Source release
    echo "Making source release"
    make_source_release "$OME_VERSION" "$git_branch"

    # Archive builds
    (
        cd "${installdir}"
        if [ "$(uname -s)" = "Linux" ]; then
            ROOTCMD=
            TAR_OPTIONS="--owner=root --group=root"
        else
            ROOTCMD=fakeroot
            TAR_OPTIONS="--format pax"
        fi
        mkdir -p "${artefactdir}/superbuild"

        echo "Archiving ome-files-bundle-${version_tag}.tar.xz"
        $ROOTCMD tar -cf - $TAR_OPTIONS "ome-files-bundle-${version_tag}" | xz > "${artefactdir}/superbuild/ome-files-bundle-${version_tag}.tar.xz"

        if [ -d "ome-files-bundle-apidoc-${OME_VERSION}" ]; then
            echo "Archiving ome-files-bundle-apidoc-${OME_VERSION}.tar.xz"
            $ROOTCMD tar -cf - $TAR_OPTIONS "ome-files-bundle-apidoc-${OME_VERSION}" | xz > "${artefactdir}/ome-files-bundle-apidoc-${OME_VERSION}.tar.xz"
        fi
    )

    # Archive sources
    cp -a ${cachedir}/source "${artefactdir}/sources"

    # Test archive
    (
        echo "Test archive functionality"
        rm -rf test
        mkdir test
        cd test

        tar -xvf "${artefactdir}/superbuild/ome-files-bundle-${version_tag}.tar.xz"
        cd ome-files-bundle-${version_tag}

        echo "Test ome-files version"
        bin/ome-files --version
        echo "Test ome-files usage"
        bin/ome-files --usage
        echo "Test ome-files help"
        bin/ome-files --help | cat

        echo "Test ome-files info version"
        bin/ome-files info --version
        echo "Test ome-files info usage"
        bin/ome-files info --usage
        echo "Test ome-files info help"
        bin/ome-files info --help | cat

    )
    echo "Complete"
}

usage() {
    cat <<EOF
Usage: $(basename $0) [options]"

Actions:
  -h         Display this help text
  -B         Build and install (default action)

Options:
  -w dir     Set workspace directory (sets defaults for all directory paths below)
  -s dir     Set source directory
  -b dir     Set build directory
  -i dir     Set installation directory
  -a dir     Set artefact directory
  -c dir     Set cache directory

  -g branch  Set git branch or tag to release from
  -G         Build from git (rather than the default source release archive)
  -n         Do not build third-party prerequisites
  -p mode    Purge cache (none|all|build|python)
  -t type    Build type (Debug|Release)
  -S system  Build system (Unix Makefiles|Ninja)
  -d         Build doxygen API reference
  -e         Run extended tests
  -j n       Build in parallel
  -v         Verbose build
  -x         Use C++11/C++14 rather than C++98

EOF
}

workspace="$(/bin/pwd)"
sourcedir="${workspace}/source"
builddir="${workspace}/build"
installdir="${workspace}/install"
artefactdir="${workspace}/artefacts"
cachedir="${workspace}/cache"

git_branch=HEAD
purge=none
build_type=Debug
build_system="Unix Makefiles"
doxygen=OFF
extended_tests=OFF
verbose=OFF
cxxdetect=OFF
parallel=
build_git=OFF
build_tp_prereqs=ON

# Parse command line options.
while getopts hBGndexvi:b:c:a:g:p:t:S:w:s:j: OPT; do
    case "$OPT" in
        h)
            usage
            exit 0
            ;;
        B)
            :
            ;;
        G)
            build_git=ON
            ;;
        n)
            build_tp_prereqs=OFF
            ;;
        d)
            doxygen=ON
            ;;
        e)
            extended_tests=ON
            ;;
        x)
            cxxdetect=ON
            ;;
        v)
            verbose=ON
            ;;
        i)
            installdir="$OPTARG"
            ;;
        b)
            builddir="$OPTARG"
            ;;
        c)
            cachedir="$OPTARG"
            ;;
        a)
            artefactdir="$OPTARG"
            ;;
        g)
            git_branch="$OPTARG"
            ;;
        p)
            purge="$OPTARG"
            ;;
        t)
            build_type="$OPTARG"
            ;;
        S)
            build_system="$OPTARG"
            ;;
        w)
            workspace="$OPTARG"
            sourcedir="${workspace}/source"
            builddir="${workspace}/build"
            installdir="${workspace}/install"
            artefactdir="${workspace}/artefacts"
            cachedir="${workspace}/cache"
            ;;
        s)
            sourcedir="$OPTARG"
            ;;
        j)
            parallel="-j $OPTARG"
            ;;
        \?)
            usage >&2
            exit 1
            ;;
    esac
done

# Remove the switches parsed above.
shift `expr $OPTIND - 1`

check_cache_validity
build
