if(WIN32)
  set(XERCES_CONFIG "ICU Debug")
  if(CONFIG MATCHES "Rel")
    set(XERCES_CONFIG "ICU Release")
  endif()

  set(XERCES_PLATFORM Win32)
  if(EP_PLATFORM_BITS STREQUAL 64)
    set(XERCES_PLATFORM x64)
  endif()

  set(XERCES_PLATFORM_PATH Win32)
  if(EP_PLATFORM_BITS STREQUAL 64)
    set(XERCES_PLATFORM_PATH Win64)
  endif()

  # VS 12.0
  if(NOT MSVC_VERSION VERSION_LESS 1800 AND MSVC_VERSION VERSION_LESS 1900)
    set(XERCES_SOLUTION VC12)
  # VS 14.0
  elseif(NOT MSVC_VERSION VERSION_LESS 1900 AND MSVC_VERSION VERSION_LESS 2000)
    set(XERCES_SOLUTION VC14)
  else()
    message(FATAL_ERROR "VS version not supported by xerces")
  endif()
endif()