# python2-virtualenv superbuild

# Set dependency list
ome_add_dependencies(python2-virtualenv
                     TYPE tool)

find_package(PythonInterp 2.7.0 REQUIRED)
set(VENV_PYTHON_EXECUTABLE "${PYTHON_EXECUTABLE}")
set(PYTHONINTERP_FOUND PYTHONINTERP_FOUND-NOTFOUND CACHE BOOL "Unset python interpreter")
set(PYTHON_EXECUTABLE PYTHON_EXECUTABLE-NOTFOUND CACHE PATH "Unset python interpreter")

ExternalProject_Add(${EP_PROJECT}
  ${OME_EP_COMMON_ARGS}
  SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}"
  BINARY_DIR "${EP_BINARY_DIR}"
  CONFIGURE_COMMAND ""
  BUILD_COMMAND ""
  INSTALL_DIR ""
  INSTALL_COMMAND ${CMAKE_COMMAND}
    "-DSOURCE_DIR:PATH=${EP_SOURCE_DIR}"
    "-DBUILD_DIR:PATH=${EP_BINARY_DIR}"
    "-DCONFIG:INTERNAL=$<CONFIG>"
    "-DEP_SCRIPT_CONFIG:FILEPATH=${EP_SCRIPT_CONFIG}"
    "-DPYTHON_EXECUTABLE=${VENV_PYTHON_EXECUTABLE}"
    "-DPIP_REQUIREMENT_FILE=${OME_EP_PYTHON2_REQUIREMENTS_FILE}"
    -P "${CMAKE_CURRENT_LIST_DIR}/install.cmake"
  DEPENDS
    ${EP_PROJECT}-prerequisites
)
